### ISSUE TITLE
Add state-plus to Stackage.

### ISSUE THREAD

**Issue by jship** [bosu/state-plus#1]
It would be helpful if state-plus was available on Stackage. This looks to be a prerequisite for getting hscope on Stackage.

Note that QuickCheck's upper bound would need to be bumped to be compatible with LTS-4.1.

Are you interested in this? I can set up Stackage's build-constraints.yml if you'd like.

**Comment by bosu** [comment]
As in pure-cdb, I am interested and will happily merge pull requests
regarding this.

Thanks.

**Comment by jship** [comment]
I submitted PR (#2) to move state-plus along towards being Stackage-ready.  Please see that PR for details.

If this PR is merged in, a new version of state-plus will have to be uploaded to Hackage.

**Comment by bosu** [comment]
Merged and uploaded, thanks!
